model:
    model: ExerciseModel
    batch_size: 64
    save_path: outputs
    exp_name: test1
    train_pkl: datasets/train_data.pkl
    val_pkl: datasets/val_data.pkl
    ex_coff: 1.0
    state_coff: 1.0
    num_epoch: 100
    num_workers: 0

arch:
    arch: 2s-AGCN
    use_bone: True # if True it will train with bone, otherwise joint will be use.
    num_point: 24 # Your num_point
    num_person: 1
    graph: "model_action.arch.graph.mygraph.Graph"
    in_channels: 2
    drop_out: 0.2

optimizer:
    optimizer: AdamW
    lr: 1e-3
    betas: [0.9,0.999]
    eps: 1e-8
    weight_decay: 0.01
    momentum_decay: ~

scheduler:
    scheduler: StepLR
    step_size: 30
    milestones: [45,55]
    gamma: 0.1

dataset:
    dataset: ExerciseDataset
    use_bone: False




