# model
model: AGCNModel
save_path: outputs
num_epoch: 50
batch_size: 32
optimizer: Adam
lr: 1e-4
scheduler: ~
milestones: ~

# arch args
len_pargs: 6
num_frames: 120
num_joints: 24
num_heads: 3
kernel_size: [3,5]
num_persons: 1
num_channles: 2
use_pes: True
config: [
    [64,  64,  16], 
    [64,  64,  16], 
    [64,  128, 32],
    [128, 128, 32],
    [128, 256, 64],
    [256, 256, 64], 
    [256, 256, 64],
    [256, 256, 64]
]

# dataset args
dataset: ExerciseDataset
train_pkl: datasets/train_data.pkl
val_pkl: datasets/val_data.pkl

